name: Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --quiet --no-interaction --no-progress --ansi

      - name: Type Coverage
        run: ./vendor/bin/pest --type-coverage --min=100
